data_filename: daxing.rds # required
school_name_auto: false # automatic school name extraction
school_name: 北京市大兴区兴华中学
ability_name_auto: true
ability_name: "基础学习能力"
test_date_auto: true
test_date: 2018-04-21
