ability:
  name:
  - 学习能力指数描述
  - 注意力描述
  - 记忆力描述
  - 自控力描述
  - 思维力描述
  - 反应力描述
  - 数学基础能力描述
  - 数字加工描述
  - 数学推理描述
  - 空间几何描述
  - 数量加工描述
  - 数学计算
  description:
  - 学习能力指数

  基础能力测评情况由大脑学习能力指数（BLAI）表示，它反映了注意力、记忆力、自控力、反应力和思维力这五个方面认知能力的综合水平，分数越高代表认知能力的综合水平发展越高。

  - 注意力
  
  注意力是大脑接收和处理个体外部和内部信息的前提,只有被注意到的信息才能得到有有效的分析和处理才能用来解决问题并形成持久的记忆。注意力包含选择注意、持续注意和分配注意三个能力维度，本次施测下每个维度都有对应的施测题目，学生分数越高，代表注意力基础能力越高。

  - 记忆力

  记忆力是人脑智力的集中体现，也是人脑比电脑更聪明的重要原因。个体的生存和发展需要不断掌握新的知识，记忆力能将这些 知识经验存储下来并合理运用。记忆连接着人的过去和未来，丰富着我们的精神生活并塑造着我们的性格。人脑包含复杂的记忆系 统，其中联系记忆、语义记忆和短时记忆是三个重要的维度，每个维度都有对应的施测题目，学生分数越高，代表记忆力基础能力越高。

  - 自控力
  
  自控力是人们能够根据目标和环境的要求，控制和改变自己的思想和行为，克服冲动并抵制诱惑，让自己的行为符合社会期许和长期目标的能力。自控力主要体现在控制冲动、抵制诱惑以及信息更新这三个维度，每个维度都有对应的施测题目，学生分数越高，代表自控力基础能力越高。

  - 思维力

  思维力是人们接收到信息后，对信息进行归纳、概括及推理的过程。生活中，我们往往不满足于耳朵所听到的、眼睛所看到的，而是要找出事物之间的内在联系和规律，解决问题并创造出新的知识。思维力可以分为思维的灵活性、深刻性和独创性这三个维度，每个维度都有对应的施测题目，学生分数越高，代表思维力基础能力越高。

  - 反应力

  反应力是对各种信息、要求和指令等做出快速反应的能力。速度是衡量反应力最重要的指标, 它体现了大脑各个系统的协调、整 合发展的水平，与整个神经网络的效率有密切关系。反应力可以从反应速度、言语速度和思维速度三个维度来测量。本次施测下每个维度都有对应的施测题目，学生分数越高，代表反应力基础能力越高。

  - 数学基础能力

  数学学科基础能力测评从数字加工、数量加工、数学计算、数学推理和空间几何这五个方面综合考察孩子的数学能力，并且测评与数学相关的核心能力。这些核心能力足以对数学能力进行科学诊断。大量证据表明，个体在这些方面的差异与数学能力的症状具有密切关系。该测评提供多种能力维度指标，包含综合的数学能力程度指标和各个能力维度指数(数字加工指数、数量加工指数、数学计算指数、数学推理指数和空间几何指数)。在测验中得到的分数越高，代表数学学科基础能力越强。

  - 数字加工

  数字加工是指个体加工数字符号，将其转换成数量表征，并运用其进行相应的认知加工的能力，是数学能力的基础。大脑顶内沟区域在数字加工中特别重要，其激活程度可以有效预测个体的数字加工效率。

  - 数学推理

  数学推理是指根据一些事实和命题，依据逻辑规则推导出一个命题的思维过程，是数学能力的核心成分。 大脑的顶叶、颞叶和额叶皮层都在数学推理过程中起着重要的作用，这些区域的激活强度可以预测数学推理能力的高低。

  - 空间几何

  空间几何能力是指对客观事物的空间形式进行观察、分析和抽象，借助几何图形对物体的运动、变化、位置关系及数量关系进行分析和思考的一种能力，是数学形象思维的核心成分。大脑的双侧顶叶和枕叶皮层在空间几何加工中尤为重要，这些脑区的激活强度可以显著预测空间几何能力的高低。

  - 数量加工

  数量加工是指准确把握具体事物的数量，而且能对抽象符号所代表的数量信息进行操作和加工的能力，是数学能力的有效预测指标。大脑的顶叶和前额叶相关脑区对数量加工至关重要，这些脑区的激活强度可以有效预测数量加工能力的高低。

  - 数学计算

  数学计算是指根据法则快速准确进行计算，并且能理解计算的算理，会通法、懂规律，能根据题目的条件探求解题的途径，寻求简洁、合理算法的能力。大脑的顶叶顶内沟区域与数学计算能力显著相关，数学计算是逻辑思维与计算技能的结合，是数学能力中的一项核心技能。


histogram:
  caption:

  本校学生总体的【name】测评的得分分布见图1-3，从图中可以看出，本校学生得分呈现正态分布，分数主要集中在【】区间中，整体表现较好。本校成绩的平均数与全区总体学生平均数相比较【大中小】，差异【显著/不显著】，t=【】，p【】0.05.

  description:
    large:

    说明在【name】测评中，本校学生整体成绩显著高于本区总体学生成绩。

    small:

    说明在【name】测评中，本校学生整体成绩显著低于本区总体学生成绩。

    equal:

    说明在【name】测评中，本校学生整体成绩与本区总体学生成绩相近。
    


boxplot:
  caption:
  本校共施测5个班级，对各个班级的【name】测评分数进行了统计，结果如下：
  

