default:
  # customer type (default to school)
  type: school
  # customer name
  name:
  # use Android Sans font, more info at
  # https://www.freechinesefont.com/simplified-traditional-droid-sans-fallback/
  text.family: Droid Sans Fallback
  score.level:
    breaks: !expr qnorm(c(0, 0.3, 0.7, 0.9, 1)) * 15 + 100
    labels: !expr LETTERS[4:1]

daxing:
  type: region
  name: 北京市大兴区

lishui:
  type: region
  name: 广东省佛山市南海区里水镇

erxiao:
  type: school
  name: 北京市第二实验小学
