# note: based on the usage of `glue` package of `R`, we use two types of open/close delimiters.
# * "<<" and ">>"" are used when the texts should be `glue`d at the top level of `glue`, and
# * "{" and "}" are used when the texts should be `glue`d at the second level of `glue`.
title: 大脑学习能力测评
subtitle: 学校集体报告
# ability and components should both contain at least five fields:
# @hlevel, @style These two fields is for one group, \code{hlevel} is the heading level, and \code{style} is used to set the custom style for the heading.
# @nameid Name identifier, must not be chinese which is not allowed if cross-reference is required
# @name Chinese name of this ability
# @description The description used for this ability
ability:
  hlevel: 2
  style: "标题2-编号"
  nameid:
  - blai
  - math
  name:
  - 基础学习能力
  - 基础数学能力
  description:
  - 基础学习能力反映了注意力、记忆力、自控力、反应力和思维力这五个方面的综合水平，分数越高代表基础学习能力的综合发展水平越高。
  - 基础数学能力是能较为迅速、容易并透彻地掌握数学知识、技能和习惯的独特的心理特征。在测验中得到的分数越高，代表基础数学能力越强。
components:
  blai:
    hlevel: 3
    style: ""
    nameid:
    - attention
    - memory
    - control
    - thinking
    - reaction
    name:
    - 注意力
    - 记忆力
    - 自控力
    - 思维力
    - 反应力
    description:
    - 注意力是大脑接收和处理个体外部和内部信息的前提,只有被注意到的信息才能得到有有效的分析和处理才能用来解决问题并形成持久的记忆。学生分数越高，代表注意力越集中。
    - 记忆力是人脑智力的集中体现，也是人脑比电脑更聪明的重要原因。个体的生存和发展需要不断掌握新的知识，记忆力能将这些 知识经验存储下来并合理运用。记忆连接着人的过去和未来，丰富着我们的精神生活并塑造着我们的性格。学生分数越高，代表记忆力越好。
    - 自控力是人们能够根据目标和环境的要求，控制和改变自己的思想和行为，克服冲动并抵制诱惑，让自己的行为符合社会期许和长期目标的能力。学生分数越高，代表自控力越强。
    - 思维力是人们接收到信息后，对信息进行归纳、概括及推理的过程。生活中，我们往往不满足于耳朵所听到的、眼睛所看到的，而是要找出事物之间的内在联系和规律，解决问题并创造出新的知识。学生分数越高，代表思维力越强。
    - 反应力是对各种信息、要求和指令等做出快速反应的能力。速度是衡量反应力最重要的指标, 它体现了大脑各个系统的协调、整合发展的水平，与整个神经网络的效率有密切关系。学生分数越高，代表反应力越强。
body:
  histogram:
    caption: 本校学生{ability_name_cn}测评的分数分布对比
    description: 本校学生总体的{ability_name_cn}测评的得分分布见图\@ref(fig:{ability_name_id}-histogram)。
  table:
    caption: 本校和各班学生{ability_name_cn}测评的整体表现详表
    description: 本校共施测{n_cls}个班级。表\@ref(tab:{ability_name_id}-tab)中展示了本校和各班的学生整体表现情况。{extra_tab}其中，**水平A**：优秀；**水平B**：良好；**水平C**：中等；**水平D**：较差。
    note:
      sig: 并且各班级的表现差异明显
      nsig: 但是各班级的表现差异不明显
      extra: # display only the condition is meeted
        condition: n_cls > 1
        content: 从学生的平均水平来看，{best_cls}学生的整体表现最好，而{worst_cls}学生的整体表现最差，{diff_msg_mean}。
  boxplot:
    caption: 本校和各班学生{ability_name_cn}测评的得分情况对比
    description: 本校和各班的{ability_name_cn}测评分数的分布区间如图\@ref(fig:{ability_name_id}-boxplot)。{extra_bp}
    note:
      sig: 并且各班级的表现差异明显
      nsig: 但是各班级的表现差异不明显
      extra:
        condition: n_cls > 1
        content: 从中位数（即得分恰好在正中间的学生，参考表\@ref(tab:{ability_name_id}-tab)查看具体数值）角度看，{best_cls_med}的总体表现最好，{worst_cls_med}的总体表现最差，{diff_msg_med}。在后期应该重点关注{worst_cls_med}，对能力不足的学生进行干预和有计划的训练。
  grading:
    caption: 本校和各班{ability_name_cn}测评的各水平人数比例
    description: 本校学生总体在{ability_name_cn}测评中各个水平的人数比例如图\@ref(fig:{ability_name_id}-grading)。每个班级的学生从等级优秀到不足的占比情况存在差异，应该重点关注在等级D中占比较大的班级对学生的{ability_name_cn}进行有计划的训练和干预。其中，**水平A**：优秀；**水平B**：良好；**水平C**：中等；**水平D**：较差。
