# note: based on the usage of `glue` package of `R`, we use two types of open/close delimiters.
# * "<<" and ">>"" are used when the texts should be `glue`d at the top level of `glue`, and
# * "{" and "}" are used when the texts should be `glue`d at the second level of `glue`.
title: 大脑学习能力测评
subtitle: 集体报告
# ability and components should both contain at least five fields:
# @hlevel, @style These two fields is for one group, \code{hlevel} is the heading level, and \code{style} is used to set the custom style for the heading.
# @nameid Name identifier, must not be chinese which is not allowed if cross-reference is required
# @name Chinese name of this ability
# @description The description used for this ability
ability:
  hlevel: 2
  style: ""
  nameid: blai
  name: BLAI指数
  description: 综合能力分数由大脑学习能力指数（BLAI）表示，它反映了注意力、记忆力、自控力、反应力这四方面认知能力的综合水平。
components:
  blai:
    hlevel: 3
    style: ""
    nameid:
    - attention
    - memory
    - reaction
    - control
    - thinking
    name:
    - 注意力
    - 记忆力
    - 反应力
    - 自控力
    - 思维力
    description:
    - 注意是大脑接收和处理个体外部和内部信息的前提，只有被注意到的信息才能得到有效的分析和处理，并用来解决问题并形成持久的记忆。
    - 记忆力是人脑智力的集中体现，也是人脑比电脑更聪明的重要原因。个体的生存和发展需要不断掌握新的知识，记忆能将这些知识经验存储下来并合理运用。记忆连接着人的过去和未来，丰富着我们的精神生活并塑造着我们的性格。
    - 反应力是对各种信息、要求和指令等做出快速反应的能力。速度是衡量反应力最重要的指标,它体现了大脑各个系统的协调、整合发展的水平，与整个神经网络的效率有密切关系。
    - 自控力是人们能够根据目标和环境的要求，控制和改变自己的思想和行为，克服冲动，并抵制诱惑，让自己的行为符合社会期许和长期目标。自控力主要体现为控制冲动的能力，抵制诱惑的能力以及信息更新的能力。
    - 思维力指人脑对客观事物的概括反映能力。良好的思维力让我们能快速的掌握概念，进行推理，并更好的认识事物及事物间的关系。人的思维力在一生中不断发展，在顺应其客观发展规律的基础上重视对思维力的培养，对于学习和生活都尤为重要。
context:
  title: 测评系统介绍
  content: |
    “大脑学习能力”测评系统（以下简称学习能力测评）由北京师范大学脑与学习科学研究中心与成都爱智游科技有限公司联合编制。“大脑学习能力”测评系统整合了国际国内脑科学研究最新成果，依据脑功能分化和整合原理，以及大脑功能可塑性原理，采用计算机化认知测试的方式，全面测查与个体学习和发展密切相关的“大脑学习能力”。同传统智力测验相比，“大脑学习能力”测评具有科学性强、实施方便、准确度高、预测效度好、可反复测试等优势，代表了当今脑力测试的新趋势。

    “大脑学习能力”测评综合考察注意力、记忆力、反应力、自控力等与人脑信息加工、学习、适应和发展密切相关的重要高级功能和大脑学习能力。这些能力覆盖了大脑的核心功能网络，是人脑智慧的集中体现。大量证据表明，个体在这些能力中的表现与其智力，学习能力，社会适应能力和未来发展潜力具有密切关系。

    “大脑学习能力”测评提供多种能力维度指标，包含综合的大脑学习能力指数（Brain Learning Ablility Index, BLAI）和各个能力维度指数（注意力指数、记忆力指数、反应力指数、自控力指数）。
body:
  histogram:
    caption: 本区各年级学生{ability_name_cn}测评得分的分布情况
    description: 本区各年级学生的{ability_name_cn}测评的得分分布见图\@ref(fig:{ability_name_id}-histogram)。
  table:
    caption: 本区及各学校学生{ability_name_cn}测评的整体表现详表
    description: 本区共施测{n_school}所学校，{n_grade}个年级。表\@ref(tab:{ability_name_id}-tab)中展示了本区及各学校的学生整体表现情况。其中，**水平A**：优秀；**水平B**：良好；**水平C**：中等；**水平D**：较差。
  correlation:
    caption: 本区各年级学生{ability_name_cn}测评得分与学科成绩的相关
    description: 本区各年级学生{ability_name_cn}测评得分与学科成绩如图\@ref(fig:{ability_name_id}-correlation)所示。
suggestions:
  title:
  - 父母要以身作则
  - 鼓励和表扬
  - 尊重发展规律
  - 培养设立目标的好习惯
  - 认知能力训练
  content:
  - 父母是孩子最重要的学习榜样，所以首先要以身作则，给孩子树立一个良好的榜样，做事情的时候要专注、仔细、耐心，控制自己的脾气，灵活处理突发事件。这样，小孩在无意识的模仿学习的过程中也能慢慢的形成这些品质。
  - 当孩子全神贯注做某件事情时，建议家长要不失时机的给予鼓励和肯定。因为鼓励和表扬是对小孩行为表现的肯定，会促使小孩下次再表现出这些行为。例如，在小孩完成作业之后，对小孩说“刚刚你写作业的时候表现很认真，看到你一心一意的完成作业，妈妈感觉很佩服你！”
  - 了解孩子的认知发展特点，尊重和理解孩子，不苛求孩子。例如：一般7—10岁儿童注意力能持续20分钟左右，思维力比较单一；青春期的小孩比较容易冲动等等。因此，当小孩的表现没有达到预期时，家长不要急于责骂，建议结合认知能力发展规律寻找原因。
  - 只有当孩子明白自己想要做什么、应该做什么的时候，才能规范自己的行为朝着目标前进，可以鼓励孩子认真设立目标；将目标分享给同学、老师、家长，让他们监督自己；将目标写下来贴在家里，时刻提醒等。
  - 使用针对性的认知能力训练。认知能力训练主要是依据儿童认知能力发展规律，结合个体的认知能力发展特点，制定科学性的认知能力训练任务和训练日程，针对性地提高儿童认知能力水平。例如，为了加强思维力，可以让孩子每天坚持完成一些思维力训练的任务，并及时给出反馈。
