# note: based on the usage of `glue` package of `R`, we use two types of open/close delimiters.
# * "<<" and ">>"" are used when the texts should be `glue`d at the top level of `glue`, and
# * "{" and "}" are used when the texts should be `glue`d at the second level of `glue`.
title: 大脑学习能力测评
subtitle: 区县集体报告
# ability and components should both contain at least five fields:
# @hlevel, @style These two fields is for one group, \code{hlevel} is the heading level, and \code{style} is used to set the custom style for the heading.
# @nameid Name identifier, must not be chinese which is not allowed if cross-reference is required
# @name Chinese name of this ability
# @description The description used for this ability
ability:
  hlevel: 2
  style: "标题2-编号"
  nameid:
  - blai
  - math
  name:
  - 基础学习能力
  - 基础数学能力
  description:
  - 基础学习能力反映了注意力、记忆力、自控力、反应力和思维力这五个方面的综合水平，分数越高代表基础学习能力的综合发展水平越高。
  - 基础数学能力是能较为迅速、容易并透彻地掌握数学知识、技能和习惯的独特的心理特征。基础数学能力测评从数字加工、数量加工、数学计算、数学推理和空间几何这五个方面综合考察孩子的数学能力。在测验中得到的分数越高，代表基础数学能力越强。
components:
  blai:
    hlevel: 3
    style: ""
    nameid:
    - attn
    - mmry
    - ctrl
    - thnk
    - rctn
    name:
    - 注意力
    - 记忆力
    - 自控力
    - 思维力
    - 反应力
    description:
    - 注意力是大脑接收和处理个体外部和内部信息的前提,只有被注意到的信息才能得到有有效的分析和处理才能用来解决问题并形成持久的记忆。注意力包含选择注意、持续注意和分配注意三个能力维度，本次施测下每个维度都有对应的施测题目，学生分数越高，代表注意力越集中。
    - 记忆力是人脑智力的集中体现，也是人脑比电脑更聪明的重要原因。个体的生存和发展需要不断掌握新的知识，记忆力能将这些 知识经验存储下来并合理运用。记忆连接着人的过去和未来，丰富着我们的精神生活并塑造着我们的性格。人脑包含复杂的记忆系统，其中联系记忆、语义记忆和短时记忆是三个重要的维度，每个维度都有对应的施测题目，学生分数越高，代表记忆力越好。
    - 自控力是人们能够根据目标和环境的要求，控制和改变自己的思想和行为，克服冲动并抵制诱惑，让自己的行为符合社会期许和长期目标的能力。自控力主要体现在控制冲动、抵制诱惑以及信息更新这三个维度，每个维度都有对应的施测题目，学生分数越高，代表自控力越强。
    - 思维力是人们接收到信息后，对信息进行归纳、概括及推理的过程。生活中，我们往往不满足于耳朵所听到的、眼睛所看到的，而是要找出事物之间的内在联系和规律，解决问题并创造出新的知识。思维力可以分为思维的灵活性、深刻性和独创性这三个维度，每个维度都有对应的施测题目，学生分数越高，代表思维力越强。
    - 反应力是对各种信息、要求和指令等做出快速反应的能力。速度是衡量反应力最重要的指标, 它体现了大脑各个系统的协调、整合发展的水平，与整个神经网络的效率有密切关系。反应力可以从反应速度、言语速度和思维速度三个维度来测量。本次施测下每个维度都有对应的施测题目，学生分数越高，代表反应力越强。
  math:
    hlevel: 3
    style: ""
    nameid:
    - dgtl
    - rsng
    - gmtr
    - qnty
    - cmpt
    name:
    - 数字加工
    - 数学推理
    - 空间几何
    - 数量加工
    - 数学计算
    description:
    - 数字加工是指个体加工数字符号，将其转换成数量表征，并运用其进行相应的认知加工的能力，是数学能力的基础。大脑顶内沟区域在数字加工中特别重要，其激活程度可以有效预测个体的数字加工效率。
    - 数学推理是指根据一些事实和命题，依据逻辑规则推导出一个命题的思维过程，是数学能力的核心成分。大脑的顶叶、颞叶和额叶皮层都在数学推理过程中起着重要的作用，这些区域的激活强度可以预测数学推理能力的高低。
    - 空间几何能力是指对客观事物的空间形式进行观察、分析和抽象，借助几何图形对物体的运动、变化、位置关系及数量关系进行分析和思考的一种能力，是数学形象思维的核心成分。大脑的双侧顶叶和枕叶皮层在空间几何加工中尤为重要，这些脑区的激活强度可以显著预测空间几何能力的高低。
    - 数量加工是指准确把握具体事物的数量，而且能对抽象符号所代表的数量信息进行操作和加工的能力，是数学能力的有效预测指标。大脑的顶叶和前额叶相关脑区对数量加工至关重要，这些脑区的激活强度可以有效预测数量加工能力的高低。
    - 数学计算是指根据法则快速准确进行计算，并且能理解计算的算理，会通法、懂规律，能根据题目的条件探求解题的途径，寻求简洁、合理算法的能力。大脑的顶叶顶内沟区域与数学计算能力显著相关，数学计算是逻辑思维与计算技能的结合，是数学能力中的一项核心技能。
body:
  histogram:
    caption: 本区总体学生{ability_name_cn}测评的分数分布
    description: 本区学生总体的{ability_name_cn}测评的得分分布见图\@ref(fig:{ability_name_id}-histogram)。从图中可以看出，分数主要集中于{Q1_gross}-{Q3_gross}之间。
  table:
    caption: 本区及各学校学生{ability_name_cn}测评的整体表现详表
    description: 本区共施测{n_school}所学校，其中学校名称用编码代替。表\@ref(tab:{ability_name_id}-tab)中展示了本区及各学校的学生整体表现情况。{extra_tab}其中，**水平A**：优秀；**水平B**：良好；**水平C**：中等；**水平D**：较差。
    note:
      sig: 并且各学校的表现差异明显
      nsig: 但是各学校的表现差异不明显
      extra: # display only the condition is meeted
        condition: n_school > 1
        content: 从学生的平均水平来看，{best_school}的学生表现最好，而{worst_school}的学生表现最差，{diff_msg_mean}。
  boxplot:
    caption: 本区及各学校学生{ability_name_cn}测评的得分情况对比
    description: 本区及各个学校的{ability_name_cn}测评分数的分布区间如图\@ref(fig:{ability_name_id}-boxplot)，其中学校名称用编码代替。{extra_bp}
    note:
      sig: 并且各学校的表现差异明显
      nsig: 但是各学校的表现差异不明显
      extra:
        condition: n_school > 1
        content: 从中位数（即得分恰好在正中间的学生，参考表\@ref(tab:{ability_name_id}-tab)查看具体数值）角度看，{best_school_med}的表现最好，{worst_school_med}的表现最差，{diff_msg_med}。在后期应该重点关注{worst_school_med}，在该校进行相关基础能力课程的推广，对该校能力不足的学生进行干预和有计划的训练。
  grading:
    caption: 本区及各学校{ability_name_cn}测评的不同水平人数比例
    description: 各个学校学生总体在{ability_name_cn}测评中各个水平的人数比例如图\@ref(fig:{ability_name_id}-grading)所示。每个学校的学生从等级优秀到不足的占比情况存在差异，应该重点关注在等级D中占比较大的学校，对该校学生的{ability_name_cn}进行有计划的训练和干预。其中，**水平A**：优秀；**水平B**：良好；**水平C**：中等；**水平D**：较差。
suggestions:
  title:
  - 重视基础学习能力和基础学科能力教育
  - 尊重中学生身心发展规律
  - 有针对性地推行基础能力训练
  content:
  - | # reserve new lines
    大量研究表明，大脑基础学习能力是预测学生学业表现的重要指标。比如，德国一项研究表明，在很多领域，大脑基础学习能力指标都是已知的预测学业成绩的最好指标。一般智力与学业成绩的相关通常在0.5左右。在另一项研究中，研究人员比较了智力因素，动机因素和两者共同作用对语文，数学和科学成绩的影响。结果发现，智力因素对语文成绩的贡献大概为45%，对数学的贡献为53%，对科学的贡献高达90%。在一项中国进行的研究中，研究人员发现，工作记忆和一般智力可以解释17.8 %的语言分数，36.4%的数学分数，而动机因素对学习只有很小的影响。上面只是列举了几个有代表性的研究案例。事实上，除了这些研究，还有很多发现都一致地强调了基础学习能力与学业表现的重要关联。

    除了一般智力因素以外，学科学习还需要一些特殊的基础学科能力。这些基础学科能力包括语文，数学，科学，艺术等各个学科学习所必需的，重要的基础性能力。这些能力区别于对学科知识的掌握，但对学科知识的掌握具有重要的影响。比如，伦敦大学学院教育学院的Emily Farran团队研究发现中小学生的空间能力与数学能力有很高的相关（0.479）。进一步的回归分析发现，在考虑了阅读能力的贡献后，空间能力仍然能很好地预测数学能力。我们在参与北京市脑计划的研究中发现，中学生认知能力和语文、数学和英语成绩的表现有显著关联。另外，对区域教育质量监测的研究发现，初中生数学成绩的不仅与与基础学习能力存在显著相关，也与数学学科基础能力，包括空间能力，计算能力，数感等能力存在密切关系，基础学习能力和基础数学能力之间也存在显著相关。基础学习能力和学科基础能力对预测学习成绩有独特的贡献。

    总之，国内外许多研究都表明基于脑科学的学生基础学习能力测评和提升可以快速、高效地评测学生学习的基础学习能力的长板和短板，并根据学生能力发展的剖面和实际情况，提供个性化、精准化的训练套餐，可以在线追踪每个学生的发展变化和进步情况，形成学生发展大数据；并且，学科基础能力与各个学科成绩存在着高相关，可以通过培养学生的学科基础能力来达到增强学科成绩的目的；此外，在重视素质教育的今天，学科基础能力的培养能让学生在纷繁复杂的信息中得到真正的能力提升，加强基础能力建设。

    值得注意的是，在未来测评的实施和报告的使用上，需要把评价深入到学习的每个环节，实现测评的常态化和过程化，这样既能减小测评误差，提高测评精度，同时也有助于建立个体的成长性档案。另外，还需要强化测评的诊断功能，强化成长性评价，从而能对学生的学习能力进行全面诊断，找出学习困难的真正原因，进而促成有针对性的训练，指导学习力的培养。第三，随着大脑测量科技的发展，一些可穿戴脑设备的快速普及和测量精度的提升，对于特殊的个体，后续可以使用更专业的大脑结构和功能测量，基因测试，基因表达测试等方式，与行为数据一起，实现对个体学习能力的更精细刻画。各区县和学校应该重视学生的基础学习能力教育，定期全面了解学生基础学习能力发展状况，为有效学习能力提升干预打下基础。
  - | # reserve new lines
    尊重初中生的认知能力发展规律，真正做到因材施教。研究表明，初中生阶段大脑外侧前额叶已经基本发育成熟，思维能力得到恒大提高。初中生抽象逻辑思维逐渐占主导地位，但具体形象成分还起重要的作用，具有强烈的求知欲和探索精神，兴趣广泛，思想活跃，表现出较高的创造欲望。

    另外，初中生内侧前额叶还处在快速发展阶段，这个时候的学生表现为自我意识，元认知能力不足；情绪控制能力差，心理波动大，容易焦虑，紧张，压力大；同时，自我控制能力发展有待提高，容易受到各种物质和精神诱惑的干扰，包括异性，游戏网络，烟酒乃至毒品的影响；最后，初中生执行能力还存在不足，很多时候虽然道理明白，但是使用这些道理和规则来指导和规范自己行为的能力还有不足。

    随着科学研究的不断深入和发展，心理学和脑科学对大脑学习与记忆的规律、大脑注意的规律、大脑自控的规律等学生核心学习能力，以及语文学习、数学学习等特定学科大脑学习的规律有了越来越深入的理解，同时也对学生青少年心理和认知发展的基本规律、大脑发育发展的基本规律有了更全面的认识。对于测评结果，我们应把握初中生思维的发展特点，目的是更好地发挥评价的导向作用，努力提高正面的积极因素，促进多元化评价的长效性。
  - | # reserve new lines
    通过科学测评揭示不同学生的学习能力特点，可以开展有针对性的学习能力训练，从而提高学习能力，促进学习表现。在这个方面，目前已经有了大量的研究证据。比如，英国诺森比亚大学的研究者Joni Holmes在国际著名发展心理学学术期刊《Developmental Science》发表研究成果，他们研究发现，对工作记忆较差的学生进行认知能力训练能够提高其工作记忆表现，同时数学能力也能得到显著的提高。耶鲁大学的认知训练研究结果发现，通过对工作记忆，注意力等的训练，可以有效提高学生的一般认知能力，同时提高他们在阅读和数学上的学习表现。其中，我们与北医六院合作，针对学生多动症的认知训练干预，也取得了显著的效果。

    另外，针对不同学科的关键学习能力进行训练，也可以有效改善学生的学科学习成绩。比如，苏黎世大学儿童医院磁共振研究中心的K. Kucian团队研究采用数字估计训练任务，对存在计算障碍的学生以及正常学生分别执行长达五周的训练。发现训练对于两组学生都有一定效果，但是对于存在计算障碍的学生而言，训练效果更大。密歇根州立大学教育学院的Yi-Ling Cheng团队采用持续40分钟的心理旋转挑战题目对学生进行训练。结果显示，相对于控制组而言，训练组学生的数学能力表现在训练后有了明显提升。

    这些已有的研究表明，基础能力测评的具体情况不仅可以代表学生的基础能力以及学科能力发展情况，我们还可以通过对某些能力欠缺的学生进行有效干预和训练，从而达到真实提高其基础学习能力的目标。这一切离不开长期的、针对性地、有效的干预措施，只有建立长效且定期的干预方案才能真正实现测评的意义，才能真正达到提高学生整体素质以及学业成绩的目的。

    总之，随着脑科学研究成果不断突破，对社会，学校和公众的普及和传播的不断加强，与学校教育实践的融入不断深入，脑科学与教育的结合在不远的将来会得到大大的加深，特别是基础能力训练必不可少，将会成为基础素质教育中的重要一环。学校在充分认识到基础学习能力以及基础学科能力的重要性的基础之上，应该全面了解和关注学生学习能力的现状和发展特征，并依据学生学习能力发展规律，结合个体的认知能力发展特点，制定科学的学习能力训练任务和训练日程，针对性地提高学生基础能力水平,从而更有效提高学生的基础学习能力和学科学习能力，进而提高学习效率，提升学业表现,并促进学生终生长远发展。
